### ISSUE TITLE
无法使用ssh功能

### ISSUE THREAD

**Issue by qishu321** [ldlb9527/kubernetes-admin-backend#1]
http://127.0.0.1:10010/terminal/pod/&podName=nginx-deployment-9456bbbf9-j287s/&namespace=default/&container=nginx
这样请求不对吗

**Comment by ldlb9527** [comment]
<picture>
  <img src="https://user-images.githubusercontent.com/53563191/175227173-2d920650-d36f-4d07-a9b0-54f41d28bf5e.jpg">
</picture>

<picture>
  <img src="https://user-images.githubusercontent.com/53563191/175227287-fd3f8737-7cf0-47e8-9e46-44f1fa9d77b3.jpg">
</picture>

用postman的websocket哦，,有条件的话前端用xterm.js，ssh同理，
http://127.0.0.1:10010/terminal/pod/nginx-deployment-9456bbbf9-j287s/default/nginx 
请求的url参数不会有&拼接这种

**Comment by qishu321** [comment]
![image](https://user-images.githubusercontent.com/95009146/175279236-d5b0b7c7-3088-4b1b-8de7-6bc13b3e031c.png)
不行啊，大佬

**Comment by ldlb9527** [comment]
我也是在学习😂 你把http://去掉试试，具体原因我今晚定位下

**Comment by ldlb9527** [comment]
我也是在学习😂你把(http://)前缀去掉试试，具体原因我今晚定位下

**Comment by qishu321** [comment]
![image](https://user-images.githubusercontent.com/95009146/175286372-c634b3e3-6c1b-4d8e-ad34-a874f1bf312a.png)
可以了，好厉害
