### ISSUE TITLE
您好，请问这个项目目前如何支持多集群配置呢？

### ISSUE THREAD

**Issue by googs1025** [ldlb9527/kubernetes-admin-backend#3]
目前我自己也在做k8s简易的管理系统，未来可能会支持多集群功能，想问下您目前的多集群配置是如何做的呢？

**Comment by ldlb9527** [comment]
用的本地文件存储配置文件 config/.kube/default/config   default为集群名称    你也可以存多个 可以考虑用数据库存实现ClusterStore接口  加载集群信息在proto.Cluster.init()中  把前端启动调试下就比较清楚了   之前写的demo比较乱

**Comment by ldlb9527** [comment]
README.md未更新  每个接口会传集群名

**Comment by googs1025** [comment]
哦哦 把不同集群的config都append到 config/.kube 这个里面，启动时读取配置文件，调用接口的时候区分一下调用哪个集群的资源 这样是吧
